# setting for search space
max_nodes: 4
channel: 16
num_cells: 5
workers: 4
search_space_name: "nas-bench-201"
dataset: "cifar10" # cifar10 cifar100 ImageNet16-120
data_path: '/mnt/cephfs/home/dengweitao/codes/NAS_Bench_201/dataset/cifar.python'
time_budget: 12000
arch_nas_dataset: "../bench/NAS-Bench-201-v1_1-096897.pth"
print_freq: 200
rand_seed: -1

#setting for algo
algorithm: ENAS
exp_name: test
track_running_stats: 1
config_path: '../config/ENAS/ENAS.config'
controller_entropy_weight: 0.0001
controller_bl_dec: 0.99
controller_train_steps: 50
controller_num_aggregate: 20
controller_num_samples: 100
